server:
  port: 8070
spring:
  application:
    name: consumer
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: test-rocketmq.wanshifu.com:9876
      default-binder: rocketmq
      bindings:
#        input:
#          destination: test_pre-release_topic_common_order_general
#          group: test-group
#          consumer:
#            tags: test-tag
        output:
          destination: test_pre-release_topic_common_order_general
feign:
  okhttp:
    enabled: true
  client:
    config:
      userClient:
        connectTimeout: 60000
        readTimeout: 60000
userClient:
  ribbon:
    listOfServers: localhost:8090