server:
  port: 8070
spring:
  application:
    name: consumer
feign:
  okhttp:
    enabled: true
  client:
    config:
      userClient:
        connectTimeout: 60000
        readTimeout: 60000
userClient:
  ribbon:
    listOfServers: localhost:8090