spring:
  cloud:
    gateway:
      routes:
      - id: test_route
        uri: http://localhost:8070
#        predicates:
#        - name: Cookie
#          args:
#            name: mycookie
#            regexp: mycookievalue
        filters:
        - name: AddRequestHeader
          args:
            name: X-Request-color
            value: blue
  application:
    name: gateway

server:
  port: 1984
