spring:
  cloud:
    gateway:
      routes:
      - id: test_route
        uri: http://127.0.0.1:8070
        predicates:
        - Method=GET, POST
        - Path=/testRoute/**
        filters:
        - AddRequestHeader=color, blue
        - StripPrefix=1
        - MyCustom=xxx, yyy
  application:
    name: gateway

server:
  port: 1984
