server:
  port: 8090
spring:
  application:
    name: provider
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: test-rocketmq.wanshifu.com:9876
      default-binder: rocketmq
      bindings:
        input:
          destination: test_pre-release_topic_common_order_general
          group: provider
          consumer:
            tags: add-user-tag
        output:
          destination: test_pre-release_topic_common_order_general